// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMiddlewareDisposition } from "./InputMiddlewareDisposition";
import type { InputMiddlewareEffectReceipt } from "./InputMiddlewareEffectReceipt";

export type InputMiddlewareRecord = { threadId: string, inputId: string, originalText: string, selectedText: string | null, disposition: InputMiddlewareDisposition, effect: InputMiddlewareEffectReceipt | null, };
